#lang racket

(require setup/getinfo)

(define version-number
  (match (get-info '("fulmar"))
    [#f "0.9.2"]
    [info (info 'version)]))

(define generated-string
  (format "/* This file was generated by fulmar version ~a. */~n~n" version-number))

(provide version-number
         generated-string)
