#lang racket

(define version-number
  '0.9.2)

(define generated-string
  (format "/* This file was generated by fulmar version ~s. */~n~n" version-number))

(provide version-number
         generated-string)
