#lang racket

(require "fulmar-core.rkt")
(require "core-chunk.rkt")
(require "writer.rkt")
(require "io.rkt")
(require "version.rkt")

; main for fulmar

(define cmdln-line-length (make-parameter 80))
(define cmdln-input-location (make-parameter #false))
(define cmdln-output-location (make-parameter #false))
(define cmdln-path (make-parameter #false))

;TODO: add checks to line length argument in case string is not a number (currently converts any input string into integer silently)
(define (string->integer str)
  (foldl (λ (i t) (+ (* t 10) i))
         0
         (map (λ (c) (- (char->integer c)
                        (char->integer #\0)))
              (string->list str))))

(command-line #:program "fulmar"
              #:once-each
              [("-i" "--in") input
                             "Specify input file"
                             (cmdln-input-location input)]
              [("-o" "--out") output
                              "Specify output file"
                              (cmdln-output-location output)]
              [("-l" "--line-length") length
                                      "Specify the length of a line (soft limit)"
                                      (cmdln-line-length (string->integer length))]
              [("-p" "--path") path
                               "Specfy path for included files - currently limited to one directory"
                               (cmdln-path path)]
              #:args non-flag-args (if (or (and (<= 1 (length non-flag-args))
                                                (cmdln-input-location))
                                           (and (<= 2 (length non-flag-args))
                                                (cmdln-output-location)))
                                       (error "Malformed input. Use -h or --help for more information.")
                                       (let* ([source (cond [(cmdln-input-location)]
                                                            [(< 0 (length non-flag-args)) (first non-flag-args)]
                                                            [else (current-input-port)])]
                                              [destination (cond [(cmdln-output-location)]
                                                                 [(< 1 (length non-flag-args)) (second non-flag-args)]
                                                                 [else (current-output-port)])]
                                              [version-chunk (comment-env-chunk (concat-chunk "This file was generated by fulmar version "
                                                                                              version-number
                                                                                              "."))]
                                              [context (construct-context (cmdln-line-length))]
                                              [path (cond [(cmdln-path)]
                                                          [else (current-directory)])])
                                         (print-code! (write-nekot (transform-chunks (cons version-chunk
                                                                                           (read-eval-chunks! source
                                                                                                              path))
                                                                                     context))
                                                      destination))))
