#lang racket

(require setup/getinfo)

(define version-number
  "0.9.2")
  ;((get-info '("fulmar")) 'version))

(define generated-string
  (format "/* This file was generated by fulmar version ~a. */~n~n" version-number))

(provide version-number
         generated-string)
